# Generated by Django 4.0.6 on 2022-08-19 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0002_alter_id_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="pattern",
            field=models.CharField(
                help_text="Case-sensitive. A missing trailing slash does also match to files which start with the name of the pattern, e.g., '/admin' matches /admin.html too. Some major search engines allow an asterisk (*) as a wildcard and a dollar sign ($) to match the end of the URL, e.g., '/*.jpg$'.",
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(254)],
                verbose_name="pattern",
            ),
        ),
    ]
